### ISSUE TITLE
Torrent APIv2 返回结果里新增 torrent direct download 地址

### ISSUE THREAD

**Issue by yaqinking** [BangumiMoe/rin-webui#3]
是否可以考虑下新增 torrent direct download 地址，magnet 链接获取 meta 信息时间太久了 T_T
![image](https://cloud.githubusercontent.com/assets/6315031/15595864/2611717e-23f5-11e6-8238-50c74ee27d50.png)

像（key 乃们决定个，示例如下）
`"download":"https://bangumi.moe/download/torrent/57477d392165b9ba0c485981/%E3%80%90KNA%E5%AD%97%E5%B9%95%E7%B5%84%E3%80%91%E3%80%90%E5%B0%91%E5%A5%B3%E8%88%87%E6%88%B0%E8%BB%8A%20GIRLS%20und%20PANZER%E3%80%91[%E5%8A%87%E5%A0%B4%E7%89%88][BDRIP][1280x720][%E7%B9%81%E9%AB%94%E5%A4%96%E6%8E%9B].torrent"`

这样 _(:3 」∠)_

**Comment by phoenixlzx** [comment]
这个 link 本身就是 `/download/[torrent_id]/[filename]` 的形式，你只需要知道 `torrent_id` 就可以自己拼接下载地址了。文件名 `filename` 随意。

所以其实你自己拼接的这个下载地址也是可以用的呀。

**Comment by yaqinking** [comment]
嗯，了解。
~~试了下原来 `filename` 是随意的（ry~~

**Comment by tengattack** [comment]
建议可以是 `[torrent_infohash].torrent` 或者是 `[torrent_title].torrent`

**Comment by yaqinking** [comment]
down 下来之后自动新建任务之后就自动进 trash 了，文件名什么的不重要（
不过最后执行拼接的时候还是用 title
